import PDFDocument from 'pdfkit'
import {
  bookingReference,
  fmtDate,
  fmtMoney,
} from './emailTemplates.js'

function nightsBetween(checkIn, checkOut) {
  const ms = new Date(checkOut) - new Date(checkIn)
  if (!Number.isFinite(ms) || ms <= 0) return 1
  return Math.max(1, Math.ceil(ms / (1000 * 60 * 60 * 24)))
}

function drawRow(doc, label, value, y) {
  doc.font('Helvetica-Bold').fontSize(10).fillColor('#374151').text(label, 50, y, { width: 170 })
  doc.font('Helvetica').fillColor('#111827').text(String(value ?? '-'), 230, y, { width: 315 })
  return y + 22
}

/**
 * Generate a printable booking reference PDF for hotel reception.
 */
export function generateBookingVoucherPdf(booking) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 })
    const chunks = []

    doc.on('data', (chunk) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const ref = bookingReference(booking.id)
    const hotel = booking.hotel || {}
    const room = booking.roomType || {}
    const guest = booking.user || {}
    const payment = booking.payment || {}
    const nights = nightsBetween(booking.checkIn, booking.checkOut)

    doc
      .rect(0, 0, doc.page.width, 92)
      .fill('#14532d')
    doc
      .fillColor('#ffffff')
      .font('Helvetica-Bold')
      .fontSize(22)
      .text('Booking Lanka', 50, 28)
    doc
      .font('Helvetica')
      .fontSize(11)
      .text('Official booking reference — present at hotel reception', 50, 58)

    doc.fillColor('#111827').font('Helvetica-Bold').fontSize(18).text('Booking Confirmation Voucher', 50, 118)
    doc
      .font('Helvetica')
      .fontSize(11)
      .fillColor('#6b7280')
      .text(`Reference: ${ref}  •  Booking ID: ${booking.id}`, 50, 144)

    doc
      .moveTo(50, 168)
      .lineTo(doc.page.width - 50, 168)
      .strokeColor('#e5e7eb')
      .stroke()

    let y = 188
    doc.font('Helvetica-Bold').fontSize(12).fillColor('#15803d').text('Guest & stay details', 50, y)
    y += 24

    y = drawRow(doc, 'Guest name', guest.displayName || guest.email || '-', y)
    y = drawRow(doc, 'Guest email', guest.email || '-', y)
    y = drawRow(doc, 'Guests', booking.guests ?? 1, y)
    y = drawRow(doc, 'Rooms booked', booking.rooms ?? 1, y)
    y = drawRow(doc, 'Nights', nights, y)
    y = drawRow(doc, 'Check-in', fmtDate(booking.checkIn), y)
    y = drawRow(doc, 'Check-out', fmtDate(booking.checkOut), y)

    y += 10
    doc.font('Helvetica-Bold').fontSize(12).fillColor('#15803d').text('Hotel & room', 50, y)
    y += 24

    y = drawRow(doc, 'Hotel name', hotel.name || '-', y)
    y = drawRow(doc, 'Hotel address', hotel.address || '-', y)
    y = drawRow(doc, 'Room type', room.name || '-', y)
    y = drawRow(doc, 'Room number', 'Assigned at check-in', y)
    if (hotel.checkInTime) y = drawRow(doc, 'Hotel check-in time', hotel.checkInTime, y)
    if (hotel.checkOutTime) y = drawRow(doc, 'Hotel check-out time', hotel.checkOutTime, y)

    y += 10
    doc.font('Helvetica-Bold').fontSize(12).fillColor('#15803d').text('Payment details', 50, y)
    y += 24

    y = drawRow(doc, 'Payment status', booking.status === 'PAID' ? 'Paid' : booking.status || '-', y)
    y = drawRow(doc, 'Amount paid', fmtMoney(booking.totalAmount, booking.currency), y)
    y = drawRow(doc, 'Currency', booking.currency || 'USD', y)
    if (payment.provider) y = drawRow(doc, 'Payment provider', payment.provider, y)
    if (payment.gatewayRef) {
      const refLabel =
        payment.gatewayRef.length > 28
          ? `${payment.gatewayRef.slice(0, 28)}…`
          : payment.gatewayRef
      y = drawRow(doc, 'Transaction ref', refLabel, y)
    }
    if (payment.capturedAt) y = drawRow(doc, 'Paid on', fmtDate(payment.capturedAt), y)

    y += 18
    doc
      .roundedRect(50, y, doc.page.width - 100, 72, 8)
      .fillAndStroke('#f0fdf4', '#bbf7d0')

    doc
      .fillColor('#14532d')
      .font('Helvetica-Bold')
      .fontSize(11)
      .text('Important', 64, y + 14)
    doc
      .font('Helvetica')
      .fontSize(10)
      .fillColor('#166534')
      .text(
        'This document confirms your paid reservation. Please show this voucher (printed or on your phone) at the hotel reception along with a valid photo ID.',
        64,
        y + 32,
        { width: doc.page.width - 128 }
      )

    doc
      .fontSize(9)
      .fillColor('#9ca3af')
      .text(
        `Generated by Booking Lanka • ${new Date().toLocaleString('en-GB')}`,
        50,
        doc.page.height - 60,
        { align: 'center', width: doc.page.width - 100 }
      )

    doc.end()
  })
}
